### ISSUE TITLE
Suggest bot base functionality 

### ISSUE THREAD

**Issue by Markusplay** [srkpi/suggest-bot#1]
Suggest bot task 
On the command /start bot should send greeting message to the user.
Then, when user sends message to the bot, the bot copying this message to the feedback team group. When someone in this group replying to the message, bot sends this answer to the user. 
It must support all type of files and formatted messages.

Every user request should contain ticket. Ticker template: "Запит #TuserId від @username"

**Comment by ETLARIS** [comment]
Task completed.
