### ISSUE TITLE
Requests tracking system

### ISSUE THREAD

**Issue by Markusplay** [srkpi/suggest-bot#2]
Enhance the feedback bot by adding a queue system for unanswered requests and a button-based approval workflow, allowing administrators to manage incoming feedback more efficiently.
Request statuses: "🔴Не оброблено", "🟡Взято у роботу", "🟢Оброблено"

New requests automatically have "Не оброблено" status.

The status should be written in the ticket message. 
Example:
Запит #T883934903 від @kapengagen691
Статус -🔴Не оброблено

Under the ticket, there should be 2 buttons: "Взяти у роботу" і "Оброблено". When the moderator clicks on the button, the bot must update the status of the ticket, by editing it

When the request has status "Оброблено", no button should be shown under the ticket.

**Comment by ETLARIS** [comment]
Completed.
