### ISSUE TITLE
Ban system

### ISSUE THREAD

**Issue by Markusplay** [srkpi/suggest-bot#3]
Command: /ban @username or a button "🚫Ban" under the ticket
Only chat administrators can use it.
After successful execution, the bot sends confirmation "🚫@username заблокований."

Command: /unban @username or a button "🔙Unban" under the ticket
Only chat administrators can use it.
After successful execution, the bot sends confirmation "🔙 @username розблокований."

Command: /banned_users
The command returns a list of all blocked users in the chat.
Everyone in the moderator chat can use it.
After successful execution, the bot sends the list
"Заблоковані користувачі:

1) @user1
2) @user2
...

When the "Ban" button is pressed, edit the button to "Unban". It works in the opposite order.

Data about banned users must be stored and do not reset between deploys or changes in the code

**Comment by ETLARIS** [comment]
Completed.
